<?php

namespace Database\Seeders\At_cl;

use Illuminate\Database\Seeder;
use App\Models\At_cl\Calle; 
use Illuminate\Support\Facades\DB;// Importa el modelo Calle

class Calleseeder extends Seeder
{
    /**
    *Este método genera e inserta 10 registros aleatorios en la tabla "Calle"
     * utilizando el factory del modelo Calle.
     */
    public function run(): void
    {
        $calles = [  '10 DE JUNIO',
        '11 DE MARZO',
        '12 DE OCTUBRE',
        '25 DE MAYO',
        '27 DE ENERO',
        '27 DE FEBRERO',
        '3 DE FEBRERO',
        '4 DE ENERO',
        '9 DE JULIO',
        'A. AGUADO',
        'A. ALMONACID',
        'AV. BERUTI',
        'A. CASSANELLO',
        'AV. ARISTOBULO DEL VALLE',
        'AGUSTIN DELGADO',
        'A. STORNI',
        'A.CAMELLI',
        'CASTELLANOS',
        'A. D. V. MUXICA',
        'A. DE PALLARES',
        'A.F. MONTIEL',
        'ACERIA',
        'ADOLFO MECCA',
        'AGUAYO',
        'AGUSTIN BONEO',
        'ALASSIO',
        'ALBERTO RAMOS',
        'ALFONSO DURAN',
        'ALTO VERDE',
        'ANTONIA GODOY',
        'ANUNCIACION',
        'ARTURO ILLIA',
        'AV. FACUNDO ZUVIRIA',
        'AV. J.J.PASO',
        'AV. S.CAPUTTO',
        'AV. ALMIRANTE BROWN',
        'AV. CIRCUNVAL.',
        'AV. GRAL. PAZ',
        'AVDA. 7 JEFES',
        'AVDA. GALICIA',
        'AVDA.L.N.ALEM',
        'AVDA. SANTA FE',
        'AYACUCHO',
        'B. DIAZ',
        'B. MITRE',
        'B.DE IRIGOYEN',
        'BECK-BERNARD',
        'BLAS PARERA',
        'BOHANES',
        'BOLIVIA',
        'BRASIL',
        'BV.PELLEGRINI',
        'C. CANILLITAS',
        'C. COLON',
        'C. LARGUIA',
        'C. NAMUNCURA',
        'CANDIDO PUJATO',
        'C. ROJA ARG.',
        'C.A.LEUMANN',
        'C. AGUIRRE',
        'C. DE LA PEÑA',
        'C. DE SAAVEDRA',
        'C. E. CARRANZA',
        'C. HERMANAS',
        'CA G BELGRANO',
        'CA VEL/RESIST',
        'CAILLET BOIS',
        'CALCHINES',
        'CALLEJON ROCA',
        'CAP.GIACCHINO',
        'CARCARAES',
        'CARLOS BOSSO',
        'CARLOTA SORIA',
        'CAS.DE CORREO',
        'CASEROS',
        'CATAMARCA',
        'CDOS.BELGRANO',
        'CENTENARIO',
        'CHACABUCO',
        'CHACO',
        'CHANAES',
        'CJON. AGUIRRE',
        'CJON. BIOQUIM',
        'CJON. LABORIE',
        'CJON. MOCOVA',
        'CJON.EL SABLE',
        'CNEL. DORREGO',
        'CNEL. F. LOZA',
        'CNEL.J.MENDEZ',
        'CNEL.T.ESPORA',
        'CNGO. ECHAGUE',
        'CNGO.J.VIÃ‘AS',
        'CNO.ESPERANZA',
        'COCHABAMBA',
        'COLOMBIA',
        'COMB.MALVINAS',
        'CONTRERAS',
        'COOP.EMP.VIV.',
        'CORDOBA',
        'CORONDAS',
        'CORRIENTES',
        'CRISTO OBRERO',
        'D. COLODRERO',
        'D. FIGUEROA',
        'D. FRENCH',
        'D. MATHEU',
        'VELEZ SARSFIELD',
        'DE AZCUENAGA',
        'DE CENTENERA',
        'DE LA SALLE',
        'DE LARRECHEA',
        'DE LAS CASAS',
        'DE LOS ANDES',
        'DEFENSA',
        'HUERGO',
        'DG. S/N 11.25',
        'DG. S/N 9.25',
        'DG.S/N 100.75',
        'DG.S/N 104.75',
        'DG.S/N 120.75',
        'DG.S/N 120.95',
        'DG.S/N 126.75',
        'DG.S/N 151.25',
        'DG.S/N 171.75',
        'DG.S/N 7.25',
        'DG.S/N 78.25A',
        'DG.S/N 86.75A',
        'DG.S/N 88.75A',
        'DG.S/N 88.90A',
        'DGNAL. AGUADO',
        'DGNAL. ESPAÑA',
        'DGNAL. GOYENA',
        'DGNAL. HUDSON',
        'DGNAL. AGUIRRE',
        'DGNAL.VARELA',
        'DGO. ROMERO',
        'DIAG.ABIPONES',
        'DIAG.CERVERA',
        'DIAG.IRIGOYEN',
        'DIAG.MARTINEZ',
        'DIAG.MATTURO',
        'DIEGO NUÑEZ',
        'DOMINGO SILVA',
        'DON BOSCO',
        'DON BOSCO II',
        'DR. M.ZAVALLA',
        'DR. P.ZENTENO',
        'IRIGOYEN FREYRE',
        'DR.B.LAVAISSE',
        'DR.G.A.FESTER',
        'DR.J.AMENABAR',
        'DR.N.FASOLINO',
        'DRA. GRIERSON',
        'E. MUTTIS',
        'ECUADOR',
        'EDMUNDO ROSAS',
        'EL POZO',
        'ENTRE RIOS',
        'EST.DE ISRAEL',
        'ESTAFETA',
        'EUROPA',
        'EVA PERON',
        'F. FERNANDEZ',
        'F. M. ESQUIU',
        'F. S.M. DE ORO',
        'F.A.CHICLANA',
        'F. C.RODRIGUEZ',
        'F.VERA MUJICA',
        'FELIPE CAITO',
        'FRANCIA',
        'FRAY J. PEREZ',
        'G.PIEDRABUENA',
        'GARCIA BAÃ‘ON',
        'GARCIA VIEYRA',
        'GDOR. CRESPO',
        'GDOR. LEHMANN',
        'GDOR. M. VERA',
        'GDOR. MOLINAS',
        'GDOR. N.OROÃ‘O',
        'GOBERNADOR CANDIOTI',
        'GDOR.MENCHACA',
        'GDOR.R.FREYRE',
        'GENARO SILVA',
        'GRAL. BOLIVAR',
        'GRAL. E. LOPEZ',
        'GRAL. GUEMES',
        'GRAL. LAVALLE',
        'GRAL. MOSCONI',
        'GRAL. BALCARCE',
        'GRAL. BELGRANO',
        'GRAL. C. ALVEAR',
        'GRAL. NECOCHEA',
        'GRAL. QUIROGA',
        'GRAND BOURG',
        'GRANDOLI',
        'GUAYCURÌES',
        'GUINUANES',
        'H. C BOAGLIO',
        'H. IRIGOYEN',
        'H.DAMIANOVICH',
        'HERNANDARIAS',
        'HNO.FIGUEROA',
        'HUGO WAST',
        'I. CRESPO',
        'INDEPENDENCIA',
        'ING.T.ZAMARO',
        'ITALIA',
        'ITUZAINGO',
        'J. DE LA ROSA',
        'J. E. GOLLAN',
        'J. G. ARTIGAS',
        'J. GOROSTIAGA',
        'J. H. VIEYTES',
        'J. HERNANDEZ',
        'J. I. GORRITI',
        'J. L. BORGES',
        'J. M. ESTRADA',
        'J. M. ZUVIRIA',
        'J. RODRIGUEZ',
        'J. U. AGUIRRE',
        'J.B.AZOPARDO',
        'J.C.BUSANICHE',
        'J.D.DE SOLIS',
        'J.DE ARENALES',
        'J.F.TARRAGONA',
        'J. J. CASTELLI',
        'J.M.CAFFERATA',
        'J.M.GUTIERREZ',
        'JOSE CIBILS',
        'JOSE DIAZ',
        'JOSE DOLDAN',
        'JOSE GALISTEO',
        'JOSE PEDRONI',
        'JOSE QUINTANA',
        'JOSE R. PEREZ',
        'JOSE REINARES',
        'JUAN ARZENO',
        'JUAN B.MACIEL',
        'JUAN DE GARAY',
        'JUAN F. SEGUI',
        'JUAN J.VALLE',
        'JUAN LARREA',
        'JUAN P. LOPEZ',
        'JUAN PABLO I',
        'JUJUY',
        'JUNIN',
        'JUSTICIA',
        'L ALGARROBOS',
        'L CARDENALES',
        'L CASUARINAS',
        'L EUCALIPTUS',
        'L GUAYACANES',
        'L HORTENSIAS',
        'L IBIRA PITA',
        'L MADRESELVAS',
        'L MANDARINOS',
        'L MEMBRILLOS',
        'L. MANSILLA',
        'L. TORRENT',
        'L. Y PLANES',
        'L. DE LA TORRE',
        'L.GIANELLO(H',
        'LA CALANDRIA',
        'LA ESMERALDA',
        'LA PAMPA',
        'LA PAZ',
        'LA RIOJA',
        'LAG. DESIERTO',
        'LAMOTHE',
        'LAS ACACIAS',
        'LAS AZALEAS',
        'LAS AZUCENAS',
        'LAS CAMELIAS',
        'LAS CINACINAS',
        'LAS DALIAS',
        'LAS DIAMELAS',
        'LAS ENCINAS',
        'LAS FLORES I',
        'LAS FLORES II',
        'LAS FLORES(M',
        'LAS FRESIAS',
        'LAS GREVILEAS',
        'LAS GUINDAS',
        'LAS HIGUERAS',
        'LAS MACLURAS',
        'LAS MAGNOLIAS',
        'LAS MORAS',
        'LAS ORQUIDEAS',
        'LAS TALAS',
        'LAS TIPAS',
        'LAS TOCORITAS',
        'LAS VIOLETAS',
        'LIBERACION',
        'LIBERTAD',
        'LOS ABETOS',
        'LOS AGUARIBAY',
        'LOS ALERCES',
        'LOS ALISOS',
        'LOS AROMOS',
        'LOS CEDROS',
        'LOS CEIBOS',
        'LOS CHAÃ‘ARES',
        'LOS CHARRÃšAS',
        'LOS CLAVELES',
        'LOS CURUPIES',
        'LOS DAMASCOS',
        'LOS DURAZNOS',
        'LOS FRESNOS',
        'LOS GUARANÃES',
        'LOS INGA',
        'LOS IRUPÃ‰',
        'LOS JACINTOS',
        'LOS JAZMINES',
        'LOS LAPACHOS',
        'LOS NARANJOS',
        'LOS NEGRUCHOS',
        'LOS NOGALES',
        'LOS Ã‘ANDUBAY',
        'LOS OLMOS',
        'LOS OMBUES',
        'LOS PARAISOS',
        'LOS PERALES',
        'LOS PINOS',
        'LOS TEROS',
        'LOS TIMBOES',
        'LOS UBAJAY',
        'LOS URUNDAY',
        'LOS ZORZALES',
        'LUCIANO LEIVA',
        'LUIS BELTRAN',
        'LUIS GUANELLA',
        'M. ALBERTI',
        'M. ANICHINI',
        'MARCIAL CANDIOTI',
        'MORENO',
        'M. PADILLA',
        'M.D.DE ANDINO',
        'M.I. DE BOSSO',
        'MAIPU',
        'MALVINAS',
        'MANTOVANI',
        'MANUEL LEIVA',
        'MAR ARGENTINO',
        'MARIANO CABAL',
        'MARIANO COMAS',
        'MARTIN ZAPATA',
        'MATACOS',
        'MATEO BOOZ',
        'MBEGUÃES',
        'MENDOZA',
        'MEPENES',
        'MILLAN MEDINA',
        'MISIONES',
        'MOCORETÃES',
        'MOCOVIES',
        'MONS. MENDOZA',
        'AVELLANEDA',
        'N. CÁCERES',
        'N. R. PEÑA',
        'NAC. UNIDAS',
        'NEUQUEN',
        'OB.E.PRINCIPE',
        'OB.J.GELABERT',
        'OMAR E. VERA',
        'P. CANDIOTI',
        'P. CASTAÑADUY',
        'P. DE MENDOZA',
        'P. DE ESPINOSA',
        'PADRE CATENA',
        'PADRE GENESIO',
        'PADRE MALAVER',
        'PADRE QUIROGA',
        'PATRICIAS',
        'PAVON',
        'PEDRO DE VEGA',
        'PEDRO FERRE',
        'PEDRO GALLEGO',
        'PEDRO TAPPA',
        'PEDRO VITTORI',
        'PERU',
        'PIEDRAS',
        'PIO PANDOLFO',
        'PJE. ALMAFUERTE',
        'PJE. ARZAMENDIA',
        'PJE. BUSTAMANTE',
        'PJE. C. S. MARTIN',
        'PJE. D. DE LEIVA',
        'PJE. DE IRIARTE',
        'PJE. DEAN FUNES',
        'PJE. DEL FRESNO',
        'PJE. DIEGO RUIZ',
        'PJE. ECHEVERRIA',
        'PJE. F. J. ITURRI',
        'PJE. FRENGUELLI',
        'PJE. GRAL. GUIDO',
        'PJE. GRIGOLATTO',
        'PJE. INGENIEROS',
        'PJE. J.J.LASTRA',
        'PJE. JORGE PAEZ',
        'PJE. LARRAMENDI',
        'PJE. LOS NARDOS',
        'PJE. M.DE IRALA',
        'PJE. MAGALLANES',
        'PJE. MARGARITAS',
        'PJE. P.DE DENIS',
        'PJE. PBRO.PEREZ',
        'PJE. R.ESCALADA',
        'PJE. R.GALISTEO',
        'PJE. R.MARTINEZ',
        'PJE. S/N 100.30',
        'PJE. S/N 100.50',
        'PJE. S/N 100.70',
        'PJE. S/N 100.85',
        'PJE. S/N 100.95',
        'PJE. S/N 101.30',
        'PJE. S/N 102.30',
        'PJE. S/N 102.50',
        'PJE. S/N 102.85',
        'PJE. S/N 104.85',
        'PJE. S/N 106.50',
        'PJE. S/N 106.65',
        'PJE. S/N 106.85',
        'PJE. S/N 107.50',
        'PJE. S/N 113.50',
        'PJE. S/N 120.50',
        'PJE. S/N 126.30',
        'PJE. S/N 129.50',
        'PJE. S/N 130.60',
        'PJE. S/N 134.75',
        'PJE. S/N 136.75',
        'PJE. S/N 138.75',
        'PJE. S/N 139.50',
        'PJE. S/N 141.30',
        'PJE. S/N 143.50',
        'PJE. S/N 147.25',
        'PJE. S/N 147.50',
        'PJE. S/N 163.50',
        'PJE. S/N 167.30',
        'PJE. S/N 167.50',
        'PJE. S/N 167.70',
        'PJE. S/N 169.30',
        'PJE. S/N 169.70',
        'PJE. S/N 173.70',
        'PJE. S/N 175.30',
        'PJE. S/N 183.50',
        'PJE. S/N 189.30',
        'PJE. S/N 199.50',
        'PJE. S/N 201.30',
        'PJE. S/N 203.50',
        'PJE. S/N 207.50',
        'PJE. S/N 209.50',
        'PJE. SIMONIELLO',
        'PJE. PARAVAN R',
        'PJE. 115.50-A',
        'PJE. 115.50-B',
        'PJE. 118.50-A',
        'PJE. 130.50-A',
        'PJE. 130.50-B',
        'PJE. 131.50-B',
        'PJE. 135.50-A',
        'PJE. 145.50-B',
        'PJE. 165.30-A',
        'PJE. 165.70-A',
        'PJE. 181.50-A',
        'PJE. 32.50-B',
        'PJE. 44.50-B',
        'PJE. 52.75-D',
        'PJE. 62.25-A',
        'PJE. 62.25-C',
        'PJE. 68.25-A',
        'PJE. 82.50-A',
        'PJE. 86.50-C',
        'PJE. 90.75-A',
        'PJE. 96.50-A',
        'PJE. A.GRILLI',
        'PJE. ALELIES',
        'PJE. ALFONSO',
        'PJE. AZAHARES',
        'PJE. B. OJEDA',
        'PJE. B.ROLDAN',
        'PJE. B.SUAREZ',
        'PJE. C. BAZAN',
        'PJE. CALDERON',
        'PJE. CAYASTA',
        'PJE. CEVALLOS',
        'PJE. D. PEÃ‘A',
        'PJE. D.DE ORO',
        'PJE. DE AROCA',
        'PJE. DE GARAY',
        'PJE. DONNET',
        'PJE. F.MIGUEZ',
        'PJE. FALUCHO',
        'PJE. FERREYRA',
        'PJE. FORMOSA',
        'PJE. FRAGA',
        'PJE. G.RAWSON',
        'PJE. J.MARMOL',
        'PJE. J.PARPAL',
        'PJE. M. BOEDO',
        'PJE. M. RUIZ',
        'PJE. M.MENDEZ',
        'PJE. M.SASTRE',
        'PJE. MADEO',
        'PJE. MAIPU',
        'PJE. MARSENGO',
        'PJE. P. VIGNA',
        'PJE. PARAGUAY',
        'PJE. PARANA',
        'PJE. PAREDES',
        'PJE. PIVIDORI',
        'PJE. PUBLICO',
        'PJE. ROMERO',
        'PJE. SANABRIA',
        'PJE. SILVA',
        'PJE. TRONCOSO',
        'PJE. UNIDAD',
        'PJE. VENIALBO',
        'PJE. ZORRILLA',
        'PJE. A.DE VERA',
        'PJE. A.F.ROCA',
        'PJE. A.GENEYRO',
        'PJE. A.SAVOINI',
        'PJE. ALIGHIERI',
        'PJE. ANGELELLI',
        'PJE. BAIGORRIA',
        'PJE. BARILOCHE',
        'PJE. BONAZZOLA',
        'PJE. C.AREVALO',
        'PJE. CARRASCO',
        'PJE. CERVANTES',
        'PJE. CHUBUT',
        'PJE. CINGOLANI',
        'PJE. CULLEN',
        'PJE. DE ANDREA',
        'PJE. DE GUZMAN',
        'PJE. DEL CAMPO',
        'PJE. E.Y ANDIA',
        'PJE. F.ALDAO',
        'PJE. F.BARRETO',
        'PJE. F.PAUCKE',
        'PJE. F.SANCHEZ',
        'PJE. G.Y ESGR.',
        'PJE. GUEVARA',
        'PJE. GUIRALDES',
        'PJE. J.CABEZAS',
        'PJE. J.CALCENA',
        'PJE. J.GOLLAN',
        'PJE. J.LARGUIA',
        'PJE. JAURETCHE',
        'PJE. JUAN KOCH',
        'PJE. JURAMENTO',
        'PJE. L.BRAILLE',
        'PJE. L.M.DRAGO',
        'PJE. L.PASTEUR',
        'PJE. LAS ROSAS',
        'PJE. M.QUIROGA',
        'PJE. MANTOVANI',
        'PJE. MARECHAL',
        'PJE. MOSQUERA',
        'PJE. O.ANDRADE',
        'PJE. P.DE LEON',
        'PJE. P.LEGARRA',
        'PJE. PIZZORNO',
        'PJE. PUJATO',
        'PJE. R.ANSELMI',
        'PJE. REPUBLICA',
        'PJE. RIO NEGRO',
        'PJE. RODRIGUEZ',
        'PJE. S.AGUSTIN',
        'PJE. S.DE LEON',
        'PJE. S.LINIERS',
        'PJE. S/N 13.00',
        'PJE. S/N 13.25',
        'PJE. S/N 34.30',
        'PJE. S/N 34.50',
        'PJE. S/N 35.50',
        'PJE. S/N 40.50',
        'PJE. S/N 46.50',
        'PJE. S/N 50.80',
        'PJE. S/N 58.30',
        'PJE. S/N 62.30',
        'PJE. S/N 62.70',
        'PJE. S/N 62.75',
        'PJE. S/N 64.85',
        'PJE. S/N 7.00',
        'PJE. S/N 7.50',
        'PJE. S/N 86.75',
        'PJE. S/N 89.50',
        'PJE. S/N 9.00',
        'PJE. S/N 92.30',
        'PJE. S/N 92.70',
        'PJE. S/N 94.75',
        'PJE. S/N 95.50',
        'PJE. S/N 96.30',
        'PJE. S/N 96.70',
        'PJE. S/N 96.75',
        'PJE. S/N 96.85',
        'PJE. S/N 98.30',
        'PJE. S/N 98.50',
        'PJE. S/N 98.70',
        'PJE. SALVADOR',
        'PJE. SANTA FE',
        'PJE. SEDLACEK',
        'PJE. SOBERANIA',
        'PJE. TRABAJO',
        'PJE. VECINAL',
        'PJE. VILLEGAS',
        'PREFECT.NAVAL',
        'PRIMERA JUNTA',
        'PTE. J.A.ROCA',
        'PTE.J.D.PERON',
        'PUBLICA',
        'PUJATO CRESPO',
        'QUERANDIES',
        'QUILOAZAS',
        'R. A. REARTES',
        'R. BALBIN',
        'R. DE CASTRO',
        'R. DOMINICANA',
        'R. MARTINEZ',
        'R. PIETRANERA',
        'R.DE V.MUXICA',
        'R.P.G.FURLONG',
        'PSJ. RAMON LOFEUDO',
        'RAMON SUREDA',
        'RAUL A. TACCA',
        'RECONQUISTA',
        'REP. DE SIRIA',
        'RICARDO ALDAO',
        'RIOBAMBA',
        'RIO GALLEGO',
        'RIVADAVIA',
        'ROBERTO ARLT',
        'RODRIGUEZ',
        'RODRIGUEZ C.',
        'RUPERTO GODOY',
        'S. DEL CARRIL',
        'S. DEL ESTERO',
        'S. GABOTO',
        'S. VALDIVIESO',
        'SALUSTIANO ZAVALIA',
        'S.F.DE ASIS',
        'S.I.DE LOYOLA',
        'S.VTE.DE PAUL',
        'S/N 102.75-B',
        'S/N 110.75-B',
        'SALTA',
        'SAN JERONIMO',
        'SAN JOSE',
        'SAN JUAN',
        'SAN LORENZO',
        'SAN LUIS',
        'SAN MARTIN',
        'SANTA CRUZ',
        'SARA FAISAL',
        'SARSOTTI',
        'SCALABRINI O.',
        'SERVANDO BAYO',
        'SGO. DE CHILE',
        'SILVA BRAGA',
        'SOLIDARIDAD',
        'SRA GUADALUPE',
        'STGO. DERQUI',
        'SUC.DE CORREO',
        'SUIPACHA',
        'T. CANDIOTI',
        'T. GONZALEZ',
        'T. MADREJÃ“N',
        'TACUARI',
        'TALCAHUANO',
        'TIMBASES',
        'TOBAS',
        'TTE.COGORNO',
        'TUCUMAN',
        'U. PEDRIEL',
        'U. SCHMIDL',
        'UNIDAD POSTAL',
        'URUGUAY',
        'V. ALSINA',
        'V.Y PINTADO',
        'VENEZUELA',
        'VICENTE ZAZPE',
        'VILLALTA F.D.',
        'VTA.OBLIGADO',
        'W. SUAREZ',
        'ZAPATA GOLLAN',
        'PJE. S/N 207.70',
        'PJE. S/N 207.30',
        'ALBERTI',
        'ALBERDI',
        'AV. PEÑALOZA',
        'PIETRANERA',
        'LOPEZ Y PLANES',
        'ITURRASPE',
        'AUTOP. ROS. / STA. FE',
        'GOROSTIAGA',
        'ANGEL CASANELLO',
        'FRENCH',
        'MATHEU',
        'NECOCHEA',
        'PJE. EVA PERON',
        'LOS MOLINOS',
        'S/N',
        '7 DE MARZO',
        'LAVAISE',
        'AZOPARDO',
        'SARMIENTO',
        'BELGRANO',
        'LOS ALELIES',
        'URQUIZA',
        'NICASIO OROÑO',
        'ESPERANZA',
        'DIQUE 1 ',
        'DEMETRIO GOMEZ',
        'ESPORA',
        'LAPRIDA',
        'LAS HERAS',       
    ];

        // Insertar en la base de datos
        foreach ($calles as $calle) {
            DB::table('calle')->insert([
                'name' => $calle,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
